/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.cyrano.internal;

import java.lang.classfile.ClassFile;
import java.lang.constant.ClassDesc;
import java.lang.constant.MethodTypeDesc;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import static java.lang.constant.ConstantDescs.CD_Object;
import static java.lang.constant.ConstantDescs.CD_int;
import static java.lang.constant.ConstantDescs.MTD_void;

/**
 * Proxy generator via JDK 25 Class-File API (JEP 484) — produces a class
 * concrete name {@code Cyrano$<SimpleName>} which implements the client interface.
 *
 * <p>No {@link java.lang.reflect.Proxy} dynamic proxy, no ASM or Byte Buddy.
 * The generated class is defined via {@link MethodHandles.Lookup#defineClass(byte[])}
 * in the package of the client interface. Benefits: AOT compatible (GraalVM, Leyden CDS),
 * readable stack traces, no {@code setAccessible(true)}.</p>
 *
 * <p>Anatomy of a proxy generated for a {@code com.acme.UserService} interface:</p>
 * <pre>
 *   package com.acme;                             // package of the interface
 *   public final class Cyrano$UserService implements com.acme.UserService, Closeable {
 *       private final MethodHandle invoker;       // CyranoInvocationHandler.invoke, bound
 *       private final Runnable closer;            // CyranoInvocationHandler.markClosed
 *       public Cyrano$UserService(MethodHandle invoker, Runnable closer) { ... }
 *       public String getUser(long id) {
 *           Object[] args = new Object[] { Long.valueOf(id) };
 *           try {
 *               return (String) invoker.invokeExact((Object) this, 0, args);
 *           } catch (RuntimeException | Error e) { throw e; }
 *             catch (Throwable e) { throw new RuntimeException(e); }
 *       }
 *       public void close() { closer.run(); }
 *   }
 * </pre>
 *
 * <p><b>Java Modules.</b> The proxy only refers to {@code java.base} types besides the interface's
 * own signatures, so the host module needs neither to read cyrano-core nor to see its internal
 * package (BUG-20261008-02). The one requirement on the host module is the one the error message
 * names: {@code opens <package> to io.vidocq.cyrano.core}, which lets cyrano-core define a class in
 * that package. cyrano-core adds the read edge to the host module itself. Clients generated by
 * cyrano-processor need no {@code opens} at all.</p>
 *
 * <p>The index passed to {@link CyranoInvocationHandler#invoke(Object, int, Object[])} corresponds to
 * the iteration order of {@code Map<Method, RequestSpec>} (which is a {@link
 * java.util.LinkedHashMap LinkedHashMap} — stable insertion order.</p>
 */
public final class CyranoProxyGenerator {

    private static final ClassDesc CD_MethodHandle =
            MethodHandle.class.describeConstable().orElseThrow();
    private static final ClassDesc CD_Runnable = Runnable.class.describeConstable().orElseThrow();
    /** {@code (Object proxy, int methodIndex, Object[] args) -> Object}, the shape of {@code invoke}. */
    private static final MethodType INVOKE_TYPE =
            MethodType.methodType(Object.class, Object.class, int.class, Object[].class);
    private static final MethodHandle HANDLER_INVOKE;

    static {
        try {
            HANDLER_INVOKE = MethodHandles.lookup().findVirtual(CyranoInvocationHandler.class, "invoke", INVOKE_TYPE);
        } catch (ReflectiveOperationException e) {
            throw new ExceptionInInitializerError(e);
        }
    }
    private static final ClassDesc CD_RuntimeException =
            RuntimeException.class.describeConstable().orElseThrow();
    private static final ClassDesc CD_Error = Error.class.describeConstable().orElseThrow();
    private static final ClassDesc CD_Throwable = Throwable.class.describeConstable().orElseThrow();
    private static final ClassDesc CD_Closeable =
            java.io.Closeable.class.describeConstable().orElseThrow();

    private CyranoProxyGenerator() {
        // utility
    }

    /**
     * Generates a proxy class implementing {@code iface}, registers it in the ClassLoader
     * via {@link MethodHandles.Lookup#defineClass(byte[])} and returns it.
     *
     * <p>Idempotent at content level — caller must hide the result
     * (see {@code CyranoProxyCache}).</p>
     */
    public static Class<?> generate(Class<?> iface, Map<Method, RequestSpec> specs) {
        List<Method> methods = new ArrayList<>(specs.keySet());
        //For inner interfaces, include the chain of enclosing classes in the
        //proxy name — otherwise three interfaces named `SpanResourceClient` in three
        //different outer classes (MP Telemetry TCK case) generate the same proxy
        // `Cyrano$SpanResourceClient` and collide (LinkageError + ClassCastException
        //between tests). `$` in the binary name is replaced by `_` in the suffix to
        //keep a single legible `Cyrano$` separator.
        String pkg = iface.getPackageName();
        String binaryWithoutPkg = pkg.isEmpty() ? iface.getName() : iface.getName().substring(pkg.length() + 1);
        String simpleName = "Cyrano$" + binaryWithoutPkg.replace('$', '_');
        //The proxy is generated in the same package as the target interface in order to be able to
        //implement it even when it is package-private, and to avoid visibility issues
        //between named modules (each module remains responsible for its own
        //proxies). Requires the user module to open its package to cyrano-core
        //(or both are in the unnamed module, test/classpath case).
        String binaryName = pkg.isEmpty() ? simpleName : pkg + "." + simpleName;
        ClassDesc thisClass = ClassDesc.of(binaryName);
        ClassDesc ifaceDesc = iface.describeConstable().orElseThrow();

        byte[] bytes = ClassFile.of().build(thisClass, cb -> {
            cb.withFlags(ClassFile.ACC_PUBLIC | ClassFile.ACC_FINAL | ClassFile.ACC_SUPER);
            //Always implements Closeable — spec MP Rest Client §8.1: all proxies must be Closeable
            cb.withInterfaceSymbols(ifaceDesc, CD_Closeable);
            cb.withSuperclass(CD_Object);
            cb.withField("invoker", CD_MethodHandle, ClassFile.ACC_PRIVATE | ClassFile.ACC_FINAL);
            cb.withField("closer", CD_Runnable, ClassFile.ACC_PRIVATE | ClassFile.ACC_FINAL);

            // Constructor: Cyrano$X(MethodHandle invoker, Runnable closer)
            cb.withMethodBody("<init>",
                    MethodTypeDesc.of(java.lang.constant.ConstantDescs.CD_void, CD_MethodHandle, CD_Runnable),
                    ClassFile.ACC_PUBLIC,
                    code -> code
                            .aload(0)
                            .invokespecial(CD_Object, "<init>", MTD_void)
                            .aload(0)
                            .aload(1)
                            .putfield(thisClass, "invoker", CD_MethodHandle)
                            .aload(0)
                            .aload(2)
                            .putfield(thisClass, "closer", CD_Runnable)
                            .return_());

            //One method per scan entry, in insertion order.
            for (int i = 0; i < methods.size(); i++) {
                Method m = methods.get(i);
                emitMethod(cb, thisClass, m, i);
            }

            //close() — spec §8.1: all proxies are Closeable.
            //closer.run() calls handler.markClosed(); after closing, invoke() throws IllegalStateException.
            cb.withMethodBody("close",
                    MethodTypeDesc.of(java.lang.constant.ConstantDescs.CD_void),
                    ClassFile.ACC_PUBLIC | ClassFile.ACC_FINAL,
                    code -> code
                            .aload(0)
                            .getfield(thisClass, "closer", CD_Runnable)
                            .invokeinterface(CD_Runnable, "run", MTD_void)
                            .return_());
        });

        //privateLookupIn needs cyrano-core to read the host module; a module may add a read edge
        //for itself (BUG-20261008-02). No-op for the unnamed module and for modules already read.
        CyranoProxyGenerator.class.getModule().addReads(iface.getModule());
        try {
            //privateLookupIn gives access to the interface package — lets you define
            //the proxy class in this package, whether public or not. For
            //interfaces of named modules, the user module must open its
            //package to cyrano-core via `opens`.
            MethodHandles.Lookup target = MethodHandles.privateLookupIn(iface, MethodHandles.lookup());
            try {
                return target.defineClass(bytes);
            } catch (LinkageError dup) {
                //The proxy has already been defined in this classloader (typically because
                //the CyranoProxyCache cache missed — can happen in
                //Arquillian/ShrinkWrap contexts where several Class<?> objects represent
                //the same interface between successive deployments sharing the same
                //application ClassLoader). Recover the already defined class instead of
                //failing — proxy idempotence is guaranteed by the stable interface signature.
                ClassLoader cl = iface.getClassLoader();
                if (cl == null) cl = ClassLoader.getSystemClassLoader();
                return Class.forName(binaryName, false, cl);
            }
        } catch (IllegalAccessException e) {
            throw new IllegalStateException(
                    "Cannot define the proxy " + binaryName
                            + " — ensure that the host module opens its package to "
                            + "'io.vidocq.cyrano.core' (opens "
                            + iface.getPackageName() + " to io.vidocq.cyrano.core).", e);
        } catch (ClassNotFoundException e) {
            throw new IllegalStateException(
                    "LinkageError on " + binaryName + " but class not found via Class.forName — "
                            + "ClassLoader inconsistency.", e);
        }
    }

    /**
     * Instantiates a proxy already generated, wired to {@code handler}.
     */
    @SuppressWarnings("unchecked")
    public static <T> T instantiate(Class<?> proxyClass, CyranoInvocationHandler handler) {
        try {
            var ctor = proxyClass.getDeclaredConstructor(MethodHandle.class, Runnable.class);
            Runnable closer = handler::markClosed;
            return (T) ctor.newInstance(HANDLER_INVOKE.bindTo(handler), closer);
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException("Failed to instantiate proxy " + proxyClass, e);
        }
    }

    private static void emitMethod(java.lang.classfile.ClassBuilder cb, ClassDesc thisClass,
                                   Method m, int methodIndex) {
        ClassDesc retDesc = m.getReturnType().describeConstable().orElseThrow();
        Class<?>[] paramTypes = m.getParameterTypes();
        ClassDesc[] paramDescs = new ClassDesc[paramTypes.length];
        for (int i = 0; i < paramTypes.length; i++) {
            paramDescs[i] = paramTypes[i].describeConstable().orElseThrow();
        }
        MethodTypeDesc methodType = MethodTypeDesc.of(retDesc, paramDescs);

        cb.withMethodBody(m.getName(), methodType,
                ClassFile.ACC_PUBLIC | ClassFile.ACC_FINAL,
                code -> {
                    // Compute slot of the Object[] local variable.
                    //Local slots: 0 = this, then each parameter according to its size.
                    int argsSlot = 1;
                    for (Class<?> p : paramTypes) {
                        argsSlot += (p == long.class || p == double.class) ? 2 : 1;
                    }

                    // Object[] args = new Object[paramTypes.length];
                    code.loadConstant(paramTypes.length);
                    code.anewarray(CD_Object);
                    int slot = 1;
                    for (int i = 0; i < paramTypes.length; i++) {
                        code.dup();
                        code.loadConstant(i);
                        Class<?> p = paramTypes[i];
                        loadAndBox(code, p, slot);
                        code.aastore();
                        slot += (p == long.class || p == double.class) ? 2 : 1;
                    }
                    code.astore(argsSlot);

                    // Bloc try { return (T) handler.invoke(methodIndex, args); }
                    var tryStart = code.newLabel();
                    var tryEnd = code.newLabel();
                    var catchRtEx = code.newLabel();
                    var catchError = code.newLabel();
                    var catchOther = code.newLabel();

                    code.labelBinding(tryStart);
                    code.aload(0);
                    code.getfield(thisClass, "invoker", CD_MethodHandle);
                    code.aload(0);
                    code.loadConstant(methodIndex);
                    code.aload(argsSlot);
                    //invokeExact is signature-polymorphic: the call-site type must be exactly
                    //(Object, int, Object[])Object, the type of the bound handler.invoke.
                    code.invokevirtual(CD_MethodHandle, "invokeExact",
                            MethodTypeDesc.of(CD_Object, CD_Object, CD_int,
                                    CD_Object.arrayType()));
                    emitReturn(code, m.getReturnType(), retDesc);
                    code.labelBinding(tryEnd);

                    // catch (RuntimeException re) { throw re; }
                    code.labelBinding(catchRtEx);
                    code.athrow();
                    // catch (Error err) { throw err; }
                    code.labelBinding(catchError);
                    code.athrow();
                    // catch (Throwable ex) { throw new RuntimeException(ex); } — invokeExact declares Throwable
                    code.labelBinding(catchOther);
                    code.astore(argsSlot + 1);
                    code.new_(CD_RuntimeException);
                    code.dup();
                    code.aload(argsSlot + 1);
                    code.invokespecial(CD_RuntimeException, "<init>",
                            MethodTypeDesc.of(java.lang.constant.ConstantDescs.CD_void, CD_Throwable));
                    code.athrow();

                    code.exceptionCatch(tryStart, tryEnd, catchRtEx, CD_RuntimeException);
                    code.exceptionCatch(tryStart, tryEnd, catchError, CD_Error);
                    code.exceptionCatch(tryStart, tryEnd, catchOther, CD_Throwable);
                });
    }

    /**
     * Loads the {@code slot} parameter on the stack and boxes it if primitive,
     * to store it in {@code Object[]}.
     */
    private static void loadAndBox(java.lang.classfile.CodeBuilder code, Class<?> type, int slot) {
        if (!type.isPrimitive()) {
            code.aload(slot);
            return;
        }
        if (type == long.class) {
            code.lload(slot);
            code.invokestatic(ClassDesc.of("java.lang.Long"), "valueOf",
                    MethodTypeDesc.of(ClassDesc.of("java.lang.Long"), java.lang.constant.ConstantDescs.CD_long));
        } else if (type == double.class) {
            code.dload(slot);
            code.invokestatic(ClassDesc.of("java.lang.Double"), "valueOf",
                    MethodTypeDesc.of(ClassDesc.of("java.lang.Double"), java.lang.constant.ConstantDescs.CD_double));
        } else if (type == float.class) {
            code.fload(slot);
            code.invokestatic(ClassDesc.of("java.lang.Float"), "valueOf",
                    MethodTypeDesc.of(ClassDesc.of("java.lang.Float"), java.lang.constant.ConstantDescs.CD_float));
        } else if (type == boolean.class) {
            code.iload(slot);
            code.invokestatic(ClassDesc.of("java.lang.Boolean"), "valueOf",
                    MethodTypeDesc.of(ClassDesc.of("java.lang.Boolean"), java.lang.constant.ConstantDescs.CD_boolean));
        } else {
            //int, short, byte, char — loaded via iload then boxed
            code.iload(slot);
            ClassDesc wrapper;
            ClassDesc prim;
            if (type == int.class) {
                wrapper = ClassDesc.of("java.lang.Integer");
                prim = java.lang.constant.ConstantDescs.CD_int;
            } else if (type == short.class) {
                wrapper = ClassDesc.of("java.lang.Short");
                prim = java.lang.constant.ConstantDescs.CD_short;
            } else if (type == byte.class) {
                wrapper = ClassDesc.of("java.lang.Byte");
                prim = java.lang.constant.ConstantDescs.CD_byte;
            } else if (type == char.class) {
                wrapper = ClassDesc.of("java.lang.Character");
                prim = java.lang.constant.ConstantDescs.CD_char;
            } else {
                throw new IllegalStateException("Unknown primitive type: " + type);
            }
            code.invokestatic(wrapper, "valueOf", MethodTypeDesc.of(wrapper, prim));
        }
    }

    /**
     * Emits the return code according to the Java type of the method:
     * cast (if necessary) then return/ireturn/lreturn/dreturn/freturn/return.
     */
    private static void emitReturn(java.lang.classfile.CodeBuilder code, Class<?> retType, ClassDesc retDesc) {
        if (retType == void.class) {
            code.pop();
            code.return_();
            return;
        }
        if (retType.isPrimitive()) {
            //Unbox from Object returned by handler.invoke
            ClassDesc wrapper;
            String unboxName;
            ClassDesc prim;
            if (retType == int.class) {
                wrapper = ClassDesc.of("java.lang.Integer"); unboxName = "intValue"; prim = java.lang.constant.ConstantDescs.CD_int;
            } else if (retType == long.class) {
                wrapper = ClassDesc.of("java.lang.Long"); unboxName = "longValue"; prim = java.lang.constant.ConstantDescs.CD_long;
            } else if (retType == double.class) {
                wrapper = ClassDesc.of("java.lang.Double"); unboxName = "doubleValue"; prim = java.lang.constant.ConstantDescs.CD_double;
            } else if (retType == float.class) {
                wrapper = ClassDesc.of("java.lang.Float"); unboxName = "floatValue"; prim = java.lang.constant.ConstantDescs.CD_float;
            } else if (retType == short.class) {
                wrapper = ClassDesc.of("java.lang.Short"); unboxName = "shortValue"; prim = java.lang.constant.ConstantDescs.CD_short;
            } else if (retType == byte.class) {
                wrapper = ClassDesc.of("java.lang.Byte"); unboxName = "byteValue"; prim = java.lang.constant.ConstantDescs.CD_byte;
            } else if (retType == char.class) {
                wrapper = ClassDesc.of("java.lang.Character"); unboxName = "charValue"; prim = java.lang.constant.ConstantDescs.CD_char;
            } else if (retType == boolean.class) {
                wrapper = ClassDesc.of("java.lang.Boolean"); unboxName = "booleanValue"; prim = java.lang.constant.ConstantDescs.CD_boolean;
            } else {
                throw new IllegalStateException("Unknown primitive return type: " + retType);
            }
            code.checkcast(wrapper);
            code.invokevirtual(wrapper, unboxName, MethodTypeDesc.of(prim));
            if (retType == long.class) code.lreturn();
            else if (retType == double.class) code.dreturn();
            else if (retType == float.class) code.freturn();
            else code.ireturn(); // int, short, byte, char, boolean
            return;
        }
        //Reference
        code.checkcast(retDesc);
        code.areturn();
    }
}



