/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.cyrano.internal;

import com.sun.net.httpserver.HttpServer;
import io.vidocq.cyrano.runtime.CyranoRestClientBuilderResolver;
import io.vidocq.cyrano.test.host.HostPingApi;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import org.eclipse.microprofile.rest.client.RestClientDefinitionException;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.Closeable;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Modifier;
import java.net.InetSocketAddress;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * {@link CyranoProxyGenerator} TDD tests — verifies that the class generated by the
 * Class-File API (JEP 484) correctly implements the interface, is named
 * {@code Cyrano$<SimpleName>}, and delegate to {@link CyranoInvocationHandler}.
 *
 * <p>In accordance with the Cyrano philosophy, verification focuses on
 * observable behavior (valid instance, delegated call) and not on bytecode inspection.</p>
 */
class CyranoProxyGeneratorTest {

    @Path("/echo")
    interface Echo {
        @GET
        @Path("/{msg}")
        String echo(@PathParam("msg") String msg);
    }

    /** Stub handler: captures the index and args, returns a fixed value. */
    @Test
    void generated_class_is_named_after_interface() {
        var entry = CyranoProxyCache.getOrGenerate(Echo.class);
        assertEquals("io.vidocq.cyrano.internal.Cyrano$CyranoProxyGeneratorTest_Echo", entry.proxyClass().getName(),
                "Proxy name is Cyrano$<name>; nested interfaces are qualified with their enclosing class to avoid collisions");
    }

    @Test
    void generated_class_implements_target_interface() {
        var entry = CyranoProxyCache.getOrGenerate(Echo.class);
        assertTrue(Echo.class.isAssignableFrom(entry.proxyClass()),
                "The proxy must implement the target interface");
    }

    @Test
    void generated_class_is_final_and_public() {
        var entry = CyranoProxyCache.getOrGenerate(Echo.class);
        int mods = entry.proxyClass().getModifiers();
        //ACC SUPER is no longer visible on the reflection side; We're just checking FINAL.
        assertTrue(Modifier.isFinal(mods),
                "The proxy must be final to prevent extension");
    }

    @Test
    void invocation_handler_receives_correct_index_and_args() throws Exception {
        // Manual handler that captures the index and args without HTTP.
        var capturing = new CapturingHandler();
        var entry = CyranoProxyCache.getOrGenerate(Echo.class);
        Echo proxy = CyranoProxyGenerator.instantiate(entry.proxyClass(), capturing);

        Object result = proxy.echo("hello");

        assertEquals(0, capturing.lastIndex, "First method -> index 0");
        assertNotNull(capturing.lastArgs);
        assertEquals(1, capturing.lastArgs.length);
        assertEquals("hello", capturing.lastArgs[0]);
        assertEquals("stub-response", result);
    }

    private static final String HOST = "cyrano.test.host";
    private static final String HOST_PACKAGE = HostPingApi.class.getPackageName();

    @TempDir
    java.nio.file.Path dir;

    /**
     * BUG-20261008-02: an application module that opens its client package to cyrano-core, as the
     * error message of the runtime fallback asks, gets a working client — without requiring
     * cyrano-core, without exporting anything, and without any command-line flag.
     */
    @Test
    void runtimeProxy_worksForAnInterfaceOfAnotherNamedModuleThatOpensItsPackage() throws Exception {
        Class<?> iface = hostInterface(HostModule.named(dir, HOST)
                .requires("io.vidocq.cyrano.mp.rest.client.api")
                .opens(HOST_PACKAGE, "io.vidocq.cyrano.core"));
        HttpServer server = HttpServer.create(new InetSocketAddress("127.0.0.1", 0), 0);
        server.createContext("/ping", ex -> {
            byte[] payload = "pong".getBytes(StandardCharsets.UTF_8);
            ex.getResponseHeaders().add("Content-Type", "text/plain");
            ex.sendResponseHeaders(200, payload.length);
            try (var os = ex.getResponseBody()) {
                os.write(payload);
            }
        });
        server.start();
        try {
            Object client = new CyranoRestClientBuilderResolver().newBuilder()
                    .baseUri(URI.create("http://127.0.0.1:" + server.getAddress().getPort()))
                    .build(iface);

            assertEquals(HOST, client.getClass().getModule().getName(), "the proxy lives in the host module");
            assertEquals("pong", iface.getMethod("ping").invoke(client));
            ((Closeable) client).close();
            var afterClose = assertThrows(InvocationTargetException.class, () -> iface.getMethod("ping").invoke(client));
            assertInstanceOf(IllegalStateException.class, afterClose.getCause(), "spec §8.1: a closed client fails");
        } finally {
            server.stop(0);
        }
    }

    /** Without the {@code opens}, building fails and the message says what to declare. */
    @Test
    void runtimeProxy_namesTheMissingOpensWhenTheHostDoesNotOpenItsPackage() throws Exception {
        Class<?> iface = hostInterface(HostModule.named(dir, HOST)
                .requires("io.vidocq.cyrano.mp.rest.client.api"));

        var failure = assertThrows(RestClientDefinitionException.class, () -> new CyranoRestClientBuilderResolver()
                .newBuilder().baseUri(URI.create("http://localhost:1")).build(iface));

        assertTrue(failure.getMessage().contains("opens " + HOST_PACKAGE + " to io.vidocq.cyrano.core"),
                failure.getMessage());
    }

    private static Class<?> hostInterface(HostModule module) throws ClassNotFoundException {
        ModuleLayer layer = module.with(HostPingApi.class).layer();
        Class<?> iface = layer.findLoader(HOST).loadClass(HostPingApi.class.getName());
        assertEquals(HOST, iface.getModule().getName());
        return iface;
    }

    /** Test handler that does not need a real HTTP transport. */
    static final class CapturingHandler extends CyranoInvocationHandler {
        int lastIndex = -1;
        Object[] lastArgs;
        CapturingHandler() {
            super(java.net.URI.create("http://unused"),
                    List.of(new RequestSpec("GET", "/echo/{msg}",
                            List.of(new ParamBinding.Path(0, "msg", null)),
                            String.class, String.class,
                            List.of(), List.of(),
                            java.util.Map.of(), java.util.Map.of(),
                            findEchoMethod())),
                    new CyranoHttpTransport());
        }
        private static java.lang.reflect.Method findEchoMethod() {
            try { return Echo.class.getMethod("echo", String.class); }
            catch (NoSuchMethodException e) { throw new AssertionError(e); }
        }
        @Override
        public Object invoke(Object proxy, int methodIndex, Object[] args) {
            this.lastIndex = methodIndex;
            this.lastArgs = args;
            return "stub-response";
        }
    }
}


