/*
 * Copyright (c) 2026 Vidocq contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 */
package io.vidocq.cyrano.internal;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Modifier;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * {@link CyranoProxyGenerator} TDD tests — verifies that the class generated by the
 * Class-File API (JEP 484) correctly implements the interface, is named
 * {@code Cyrano$<SimpleName>}, and delegate to {@link CyranoInvocationHandler}.
 *
 * <p>In accordance with the Cyrano philosophy, verification focuses on
 * observable behavior (valid instance, delegated call) and not on bytecode inspection.</p>
 */
class CyranoProxyGeneratorTest {

    @Path("/echo")
    interface Echo {
        @GET
        @Path("/{msg}")
        String echo(@PathParam("msg") String msg);
    }

    /** Stub handler: captures the index and args, returns a fixed value. */
    @Test
    void generated_class_is_named_after_interface() {
        var entry = CyranoProxyCache.getOrGenerate(Echo.class);
        assertEquals("io.vidocq.cyrano.internal.Cyrano$CyranoProxyGeneratorTest_Echo", entry.proxyClass().getName(),
                "Proxy name is Cyrano$<name>; nested interfaces are qualified with their enclosing class to avoid collisions");
    }

    @Test
    void generated_class_implements_target_interface() {
        var entry = CyranoProxyCache.getOrGenerate(Echo.class);
        assertTrue(Echo.class.isAssignableFrom(entry.proxyClass()),
                "The proxy must implement the target interface");
    }

    @Test
    void generated_class_is_final_and_public() {
        var entry = CyranoProxyCache.getOrGenerate(Echo.class);
        int mods = entry.proxyClass().getModifiers();
        //ACC SUPER is no longer visible on the reflection side; We're just checking FINAL.
        assertTrue(Modifier.isFinal(mods),
                "The proxy must be final to prevent extension");
    }

    @Test
    void invocation_handler_receives_correct_index_and_args() throws Exception {
        // Manual handler that captures the index and args without HTTP.
        var capturing = new CapturingHandler();
        var entry = CyranoProxyCache.getOrGenerate(Echo.class);
        Echo proxy = CyranoProxyGenerator.instantiate(entry.proxyClass(), capturing);

        Object result = proxy.echo("hello");

        assertEquals(0, capturing.lastIndex, "First method -> index 0");
        assertNotNull(capturing.lastArgs);
        assertEquals(1, capturing.lastArgs.length);
        assertEquals("hello", capturing.lastArgs[0]);
        assertEquals("stub-response", result);
    }

    /** Test handler that does not need a real HTTP transport. */
    static final class CapturingHandler extends CyranoInvocationHandler {
        int lastIndex = -1;
        Object[] lastArgs;
        CapturingHandler() {
            super(java.net.URI.create("http://unused"),
                    List.of(new RequestSpec("GET", "/echo/{msg}",
                            List.of(new ParamBinding.Path(0, "msg", null)),
                            String.class, String.class,
                            List.of(), List.of(),
                            java.util.Map.of(), java.util.Map.of(),
                            findEchoMethod())),
                    new CyranoHttpTransport());
        }
        private static java.lang.reflect.Method findEchoMethod() {
            try { return Echo.class.getMethod("echo", String.class); }
            catch (NoSuchMethodException e) { throw new AssertionError(e); }
        }
        @Override
        public Object invoke(Object proxy, int methodIndex, Object[] args) {
            this.lastIndex = methodIndex;
            this.lastArgs = args;
            return "stub-response";
        }
    }
}


